Leyecms/protected/controllers/SiteController.php
<?php

class SiteController extends Controller {

    /**
     * Declares class-based actions.
     */
    public function actions() {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
                'width' => 75,
                'height' => 30,
                'minLength' => 4, //最短为4位
                'maxLength' => 6,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex() {
        
        $advertisement=  Advertisement::model()->findAll();
        
        $productcount=  Product::model()->count();
        $product=  Product::model()->findAll(
                array(
                    'limit'=>3,
                    'offset'=>  rand(0,$productcount-3)
                )                
         );        
        
        $innovationcount=  Innovation::model()->count();
        $innovation= Innovation::model()->findAll(
                array(
                    'limit'=>3,
                    'offset'=>  rand(0,$innovationcount-3)
                )                
         );  
        
        
        // renders the view file 'protected/views/site/index.php'
        // using the default layout 'protected/views/layouts/main.php'
        $this->render('index',array(
            'advertisement'=>$advertisement,
            'product'=>$product,
            'innovation'=>$innovation,
        ));
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError() {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    public function actionContact() {
        $model = Contact::model()->findAll();
        $this->render('contact', array('model' => $model));
    }

    public function actionLeave() {
        $criteria = new CDbCriteria();
        $criteria->order = 'createtime desc';
        $criteria->condition='validate=1';
        $count = Leave::model()->count($criteria);
        $pages = new CPagination($count);
        // elements per page
        $pages->pageSize = 2;
        $pages->applyLimit($criteria);

        $models = Leave::model()->findAll($criteria);
        
        $Leavemodel=new Leave;
        $message='f';
        
        if(isset($_POST['Leave']))
	{
            $Leavemodel->attributes=$_POST['Leave'];
            $Leavemodel->createtime=date('Y-m-d H:i:s', time());
            //$Leavemodel->content='<h2>'.$Leavemodel->content."</h2>";
            if($Leavemodel->save()) {
                   $message='t';
                   $Leavemodel->content='';
            }

	}
        
        $this->render('leave', array(
            'models' => $models,
            'pages' => $pages,
            'leavemodel'=>$Leavemodel,
            'message'=>$message,
        ));
        
    }

    /**
     * Displays the login page
     */
    public function actionLogin() {
        $model = new LoginForm;

        // if it is ajax validation request
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        // collect user input data
        if (isset($_POST['LoginForm'])) {
            $model->attributes = $_POST['LoginForm'];
            // validate user input and redirect to the previous page if valid
            if ($model->validate() && $model->login())
                $this->redirect(array('/admin'));
        }
        // display the login form
        $this->render('login', array('model' => $model));
    }

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout() {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }
    
    public function actionProduct($tid=0){
        $criteria = new CDbCriteria();
        $criteria->order = 'id desc';
        if($tid!==0) {
            $criteria->condition='typeid=:tid';
            $criteria->params=array(':tid'=>$tid);
        }
        $count = Product::model()->count($criteria);
        $pages = new CPagination($count);
        // elements per page
        $pages->pageSize = 8;
        $pages->applyLimit($criteria);
        
        $type=  ProductType::model()->findAll();
        $models = Product::model()->findAll($criteria);
        
         $this->render('product', array(
            'models' => $models,
             'type'=> $type,
            'pages' => $pages,
        ));
    }
    
    public function actionInnovation($tid=0) {
        $criteria = new CDbCriteria();
        $criteria->order = 'id desc';
        if($tid!==0) {
            $criteria->condition='typeid=:tid';
            $criteria->params=array(':tid'=>$tid);
        }
        $count = Innovation::model()->count($criteria);
        $pages = new CPagination($count);
        // elements per page
        $pages->pageSize = 8;
        $pages->applyLimit($criteria);

        $models = Innovation::model()->findAll($criteria);
        $type= InnovationType::model()->findAll();
        
         $this->render('innovation', array(
            'models' => $models,
            'type'=> $type,
            'pages' => $pages,
        ));
    }
    
    public function actionAbout() {
         $about=About::model()->find();
         $this->render('about', array(
            'models' => $about,
        ));
    }
    
    public function actionEquipment() {
        $model = Equipment::model()->findAll();
        $this->render('equipment', array('model' => $model));
    }
    
    public function actionSearch($key='') {
        
        if($key!=='') {
           $key="%".$key."%";
           $connection=Yii::app()->db;
           $sql='(select * from tbl_product WHERE name LIKE :key) UNION ALL (select * from tbl_innovation WHERE name LIKE :key)';
           $command=$connection->createCommand($sql);
           $command->bindParam(":key",$key,PDO::PARAM_STR);
           $rows=$command->query();
           
           $criteria=new CDbCriteria();
           $pages=new CPagination($rows->rowCount);
           $pages->pageSize=8;
           $pages->applyLimit($criteria);
           
           $result=Yii::app()->db->createCommand($sql." LIMIT :offset,:limit");
           $result->bindParam(":key",$key,PDO::PARAM_STR);
           $result->bindValue(':offset', $pages->currentPage*$pages->pageSize);
           $result->bindValue(':limit', $pages->pageSize);
           $models=$result->queryAll();    

           //exit;
           if($models==null) {
                $this->render('search',array('info'=>'没有为您找到相关信息！',                
           ));
           }else {        
                $this->render('search',array(
                    'models'=>$models,
                    'pages'=>$pages,
                ));
           }
        }else {
            $this->render('search',array(
                'info'=>'您的查询条件为空值，请重输！',                
           ));
        }

    }
}

Leyecms/protected/views/site/_detail.php
<?php $i=0;?>	
<?php foreach($models as $p):?>

      <?php if($i++ % 4 == 0) {?>
           <div class="row-fluid">
		<div class="span12">
			<ul class="thumbnails">
      <?php }?>                   
				<li class="span3">                                    
					<div class="thumbnail">
						<img alt="300x200" src="<?php echo Yii::app()->request->baseUrl.$p->thumbnail;?>">
						<div class="caption">
							<h4>
								<?php echo $p->name;?>
							</h4>
                                                        
                                          <p class="text-right">
								<a href="#myModal<?php echo $p->id;?>" role="button" class="btn btn-small" data-toggle="modal">大图</a>
							</p>
						</div>
					</div>
                                    
                                        <!-- Modal -->
                                        <div id="myModal<?php echo $p->id;?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                                <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                        <h4 id="myModalLabel">描述</h4>
                                                </div>
                                                <div class="modal-body">
                                                        <img src="<?php echo Yii::app()->request->baseUrl.$p->imagepath;?>">
                                                        <hr>
                                                        <h4><?php echo $p->content;?></h4>
                                                </div>
                                                <div class="modal-footer">
                                                        <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">关闭</button>
                                                </div>
                                        </div>
				</li>
        <?php if($i % 4 == 0) {?>                     
			</ul>
		</div>
	</div>
       <?php }?> 

<?php endforeach?>

<?php
    if($i % 4 != 0 ) {
 ?>
			</ul>
		</div>
	</div>
<?php } ?>

        <div class="row-fluid">
		<div class="span9 offset3">
                        <?php $this->widget('CLinkPager', array(
                                'header'=>'',
                                'pages' => $pages,
                        ));
                        ?>
		</div>
	</div>
            

Leyecms/protected/views/site/_leftnav.php
	<div id="three" class="row-fluid">
		<div id="threeone" class="span3">
		  <ul class="nav nav-tabs nav-stacked">
                <li>
                        <?php echo CHtml::link('公司简介', array("/site/about"));?>
                </li>
                <li>
                        <?php echo CHtml::link('设备明细', array("/site/equipment"));?>
                </li>
                <li>
                        <?php echo CHtml::link('访客留言', array("/site/leave"));?>
                </li>
                <li>
                        <?php echo CHtml::link('联系我们', array("/site/contact"));?>
                </li>
		  </ul>
		</div>

Leyecms/protected/views/site/about.php
<?php $this->renderpartial('_leftnav');?>
	  
		<div class="span8">
			
			    <?php 
                                echo $models->content;
                            ?>
			 
		</div>
	    
                <div class="span1">
		</div>
	
	</div>

Leyecms/protected/views/site/contact.php
<!-- render _leftnav -->
<?php $this->renderpartial('_leftnav');?>

		<div class="span9">
			<div class="tabbable" id="tabs-787530">
				<ul class="nav nav-tabs">
                                     <?php
                                     $first=true;   
                                     foreach($model as $m) {                                                                        
                                     ?>       
                                        <li <?php if($first) {echo 'class="active"';$first=false;}?>>
						<a href="#panel-<?php echo $m->id;?>" data-toggle="tab"><?php echo $m->name;?></a>
					</li>
                                      <?php
                                        }
                                      ?>
				</ul>
				<div class="tab-content">
                                     <?php
                                        $first=true; 
                                        foreach($model as $m) {
                                     ?> 
					<div class="tab-pane <?php if($first) {echo 'active';$first=false;}?>" id="panel-<?php echo $m->id;?>">
                                            <?php echo $m->content;?>
					</div>
                                        <?php } ?>
				</div>
			</div>
		</div>
	</div>

Leyecms/protected/views/site/equipment.php
<!-- render _leftnav -->
<?php $this->renderpartial('_leftnav');?>

		<div class="span9">
			<div class="tabbable" id="tabs-787530">
				<ul class="nav nav-tabs">
                                     <?php
                                     $first=true;   
                                     foreach($model as $m) {                                                                        
                                     ?>       
                                        <li <?php if($first) {echo 'class="active"';$first=false;}?>>
						<a href="#panel-<?php echo $m->id;?>" data-toggle="tab"><?php echo $m->name;?></a>
					</li>
                                      <?php
                                        }
                                      ?>
				</ul>
				<div class="tab-content">
                                     <?php
                                        $first=true; 
                                        foreach($model as $m) {
                                     ?> 
					<div class="tab-pane  <?php if($first) {echo 'active';$first=false;}?>" id="panel-<?php echo $m->id;?>">
                                            <?php echo $m->content;?>
					</div>
                                        <?php } ?>
				</div>
			</div>
		</div>
	</div>

Leyecms/protected/views/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2>Error <?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

Leyecms/protected/views/site/index.php
	<!-- Carousel -->
	<div id="one" class="row-fluid">
		<div class="span12">
						<img alt="" src="<?php echo Yii::app()->request->baseUrl.$advertisement[0]->imagepath;?>">
		</div>
	</div>
		

	


<!-- render _leftnav -->
<?php $this->renderpartial('_leftnav');?>
<?php
	$title=array(
			"资源与环境",
			"产品与工艺"
		);
?>

		<div class="span9">
			<div class="tabbable" id="tabs-787530">
				<ul class="nav nav-tabs">
                                     <?php  
                                     for($i=0;$i<2;$i++) {                                                                       
                                     ?>       
                                        <li <?php if($i==0) {echo 'class="active"';}?>>
						<a href="#panel-<?php echo $i;?>" data-toggle="tab"><?php echo $title[$i];?></a>
					</li>
                                      <?php
                                        }
                                      ?>
				</ul>
				<div class="tab-content">
                                     <?php
                                        for($i=0;$i<2;$i++) {
							$detail=($i==0?$innovation:$product);
								
                                     ?> 
					<div class="tab-pane <?php if($i==0) {echo 'active';}?>" id="panel-<?php echo $i;?>">							
							
							<ul class="thumbnails">
                            				<?php 
									$p=0;
                                			foreach($detail as $r) {
                            					?>                                
								<li class="span4">                                    
									<div class="thumbnail">
										<img alt="300x200" src="<?php echo Yii::app()->request->baseUrl.$r->thumbnail;?>">
										<div class="caption">
											<h4>
												<?php echo $r->name;?>
											</h4>
                                                        
                                         					 <p class="text-right">
												<a href="#myModal<?php echo $r->id.$i;?>" role="button" class="btn btn-small" data-toggle="modal">大图</a>
												<?php if($p==2) { ?>
													<?php echo CHtml::link('更多', array(($i==0?"/site/innovation":"/site/product")),array('class'=>"btn btn-small"));?>
												<?php } ?>
											</p>
										</div>
									</div>
                                    
                                        			<!-- Modal -->
                                        			<div id="myModal<?php echo $r->id.$i;?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                                		<div class="modal-header">
                                                       		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                        		<h4 id="myModalLabel">描述</h4>
                                               			 </div>
                                               			 <div class="modal-body">
                                                        		<img src="<?php echo Yii::app()->request->baseUrl.$r->imagepath;?>">
                                                       		 <hr>
                                                       		 <h4><?php echo $r->content;?></h4>
                                                		</div>
                                                		<div class="modal-footer">
                                                       		 <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">关闭</button>
                                                		</div>
                                        			</div>
								</li>
                             				<?php 
									$p++;
								} ?>
							</ul>
					</div>
                                   <?php } ?>
				</div>
			</div>
		</div>

	</div>

Leyecms/protected/views/site/innovation.php
	<div id='typelink' class="row-fluid">
		<div class="span12">
                    <strong>分类浏览:</strong>
                    <?php foreach ($type as $t) {?>
                        <?php echo CHtml::link($t->type, array("/site/innovation",'tid'=>$t->id));?>
                    <?php
                    }?>
		</div>
	</div>

<?php if($models==null){ ?>
    	<div class="row-fluid">
		<div class="span12">
                    <h4 class="text-center">暂无相关信息！</h4>
		</div>
	</div>
<?php
}
else {
    $this->renderpartial('_detail',
         array('models'=>$models,
         'pages' => $pages));
}
?>

Leyecms/protected/views/site/leave.php
<!-- leave -->
<?php foreach($models as $m):?>
<hr>
<div class="row-fluid">
		<div class="span3">
			<blockquote>
                                <h3><?php echo CHtml::encode($m->name);?></h3>
				<small><cite><?php echo $m->createtime;?></cite></small>
			</blockquote>
		</div>
		<div class="span9">	
                        
                            <h4><?php echo CHtml::encode($m->content);?></h4>	
                        
			<blockquote>
                            
                            <h4><?php echo CHtml::encode($m->comment);?></h4>
                            
                            <small><cite>管理员</cite></small>
			</blockquote>
		</div>
	</div>

<?php endforeach?>
 
<!-- 翻页-->
        <div class="row-fluid">
		<div class="span9 offset3">
                        <?php $this->widget('CLinkPager', array(
                                'header'=>'',
                                'pages' => $pages,
                        ));
                        ?>
		</div>
	</div>
        
	<hr>
        <!-- comment -->
	<div class="row-fluid">
		<div class="span2">
                    <?php
                        if($message=='t') {
                    ?>
                    	<div class="alert alert-info">
				 <button type="button" class="close" data-dismiss="alert">×</button>
                                   <h4>
					恭喜!
                                   </h4>您的留言已成功，请等待管理员审核.
			</div>
                    
                    <?php
                    } else {
                    ?>
			<div class="alert">
				 <button type="button" class="close" data-dismiss="alert">×</button>
                                   <h4>
					注意!
                                   </h4>只有经过管理员审核的留言才会显示.
			</div>
                    <?php } ?>
		</div>
		<div class="span10">
			<?php
                                    $form = $this->beginWidget('CActiveForm', array(
                                    'id' => 'leave-form',
                                    'enableAjaxValidation' => false,
                                     'htmlOptions'=>array('class'=>'form-horizontal'),
                        ));
                        ?>
				<div class="control-group">
                                        <?php echo $form->labelEx($leavemodel,'name',array('class'=>'control-label')); ?>
					<div class="controls">
						<?php echo $form->textField($leavemodel,'name'); ?>
                                                <?php echo $form->error($leavemodel,'name',array('class'=>'help-inline','style'=>'color:red')); ?>
					</div>
				</div>
				<div class="control-group">
					 <?php echo $form->labelEx($leavemodel,'email',array('class'=>'control-label')); ?>
					<div class="controls">
						<?php echo $form->textField($leavemodel,'email'); ?>
                                                <?php echo $form->error($leavemodel,'email',array('class'=>'help-inline','style'=>'color:red')); ?>
					</div>
				</div>
				<div class="control-group">
					<?php echo $form->labelEx($leavemodel,'tel',array('class'=>'control-label')); ?>
					<div class="controls">
                                                <?php echo $form->textField($leavemodel,'tel'); ?>
                                                <?php echo $form->error($leavemodel,'tel',array('class'=>'help-inline','style'=>'color:red')); ?>
					</div>
				</div>
				<div class="control-group">
                                        <?php echo $form->labelEx($leavemodel,'content',array('class'=>'control-label')); ?>
					<div class="controls">						
                                                <?php echo $form->textArea($leavemodel,'content',array('rows'=>6, 'class'=>'span5')); ?>
                                                <?php echo $form->error($leavemodel,'content',array('class'=>'help-inline','style'=>'color:red')); ?>
					</div>
				</div>
				<div class="control-group">
					<div class="controls">
						 <?php echo CHtml::submitButton('提交',array('class'=>'btn')); ?>
					</div>
				</div>
			<?php $this->endWidget(); ?>
		</div>
	</div>

Leyecms/protected/views/site/login.php
<!-- login -->

	<div class="row-fluid"  style="margin-bottom:300px;">
		<div class="span3">
		</div>
		<div class="span9">
			<h3>
				Login.
			</h3>
                        <?php $form=$this->beginWidget('CActiveForm', array(
                                'id'=>'login-form',
                                'enableClientValidation'=>true,
                                'clientOptions'=>array(
                                        'validateOnSubmit'=>true,
                                ),
                                'htmlOptions'=>array('class'=>'form-horizontal'),
                                )); ?>
				<div class="control-group">
                                        <?php echo $form->labelEx($model,'username',array('class'=>'control-label')); ?>
                                        <div class="controls">
						<?php echo $form->textField($model,'username'); ?>
                                                <?php echo $form->error($model,'username',array('class'=>'help-inline','style'=>'color:red')); ?>
					</div>
                                        
				</div>
				<div class="control-group">
					<?php echo $form->labelEx($model,'password',array('class'=>'control-label')); ?>
					<div class="controls">
						<?php echo $form->passwordField($model,'password'); ?>
                                                <?php echo $form->error($model,'password',array('class'=>'help-inline','style'=>'color:red')); ?>
					</div>
				</div>
                    
                    <?php if(CCaptcha::checkRequirements()): ?>
                                <div class="control-group">
					<?php echo $form->labelEx($model,'verifyCode',array('class'=>'control-label')); ?>
                                        
					<div class="controls">
						<?php echo $form->textField($model,'verifyCode'); ?>
                                                <?php $this->widget('CCaptcha',array('buttonLabel' => '看不清','clickableImage'=>true,'showRefreshButton'=>false)); ?>
                                                <?php echo $form->error($model,'verifyCode',array('class'=>'help-inline','style'=>'color:red')); ?>
					</div>
				</div>
                    <?php endif; ?>
                    
				<div class="control-group">
					<div class="controls">
						 <label class="checkbox">
                                                     <?php echo $form->checkBox($model,'rememberMe'); ?>记住我
                                                 </label> 
                                                 <?php echo $form->error($model,'rememberMe'); ?>
                                                 <?php echo CHtml::submitButton('登录',array('class'=>'btn')); ?>
					</div>
				</div>
			<?php $this->endWidget(); ?>
		</div>
	</div>

Leyecms/protected/views/site/product.php
	<div id='typelink' class="row-fluid">
		<div class="span12">
                    <strong>分类浏览:</strong>
                    <?php foreach ($type as $t) {?>
                        <?php echo CHtml::link($t->type, array("/site/product",'tid'=>$t->id));?>
                    <?php
                    }?>
		</div>
	</div>

<?php if($models==null){ ?>
    	<div class="row-fluid">
		<div class="span12">
                    <h4 class="text-center">暂无相关信息！</h4>
		</div>
	</div>
<?php
}
else {
    $this->renderpartial('_detail',
         array('models'=>$models,
         'pages' => $pages));
}
?>

Leyecms/protected/views/site/search.php
<?php if(isset($models)) {
     $i=0;
     $ij=0;
     foreach ($models as $p) {
?>         
      <?php if($i++ % 4 == 0) {?>
           <div class="row-fluid">
		<div class="span12">
			<ul class="thumbnails">
      <?php }?>                   
				<li class="span3">
					<div class="thumbnail">
						<img alt="300x200" src="<?php echo Yii::app()->request->baseUrl.$p['thumbnail'];?>">
						<div class="caption">
							<h4>
								<?php echo $p['name'];?>
							</h4>
                                                        
                                          <p>
								<a href="#myModal<?php echo $ij;?>" role="button" class="btn" data-toggle="modal">大图</a>
							</p>
						</div>
					</div>
                                    
                                        <!-- Modal -->
                                        <div id="myModal<?php echo $ij;?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                                <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                        <h4 id="myModalLabel">描述</h4>
                                                </div>
                                                <div class="modal-body">
                                                        <img src="<?php echo Yii::app()->request->baseUrl.$p['imagepath'];?>">
                                                        <hr>
                                                        <h4><?php echo $p['content'];?></h4>
                                                </div>
                                                <div class="modal-footer">
                                                        <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">关闭</button>

                                                </div>
                                        </div>
				</li>
        <?php if($i % 4 == 0) {?>                     
			</ul>
		</div>
	</div>
       <?php }?> 

     <?php 
           $ij++;
     } ?>

<?php
    if($i % 4 != 0 ) {
 ?>
			</ul>
		</div>
	</div>
<?php } ?>

        <div class="row-fluid">
		<div class="span9 offset3">
                        <?php $this->widget('CLinkPager', array(
                                'header'=>'',
                                'pages' => $pages,
                        ));
                        ?>
		</div>
	</div>
            



<?php
 
}else {
?>
       	<div class="row-fluid">
		<div class="span12">
                    <h4 class="text-center"><?php echo $info;?></h4>
		</div>
	</div>

<?php }?>