Leyecms/protected/controllers/SiteController.php
<?php

class SiteController extends Controller {

    /**
     * Declares class-based actions.
     */
    public function actions() {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
                'width' => 75,
                'height' => 30,
                'minLength' => 4, //最短为4位
                'maxLength' => 6,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex() {
        
        $advertisement=  Advertisement::model()->findAll();
        
        $productcount=  Product::model()->count();
        $product=  Product::model()->findAll(
                array(
                    'limit'=>3,
                    'offset'=>  rand(0,$productcount-3)
                )                
         );        
        
        $innovationcount=  Innovation::model()->count();
        $innovation= Innovation::model()->findAll(
                array(
                    'limit'=>3,
                    'offset'=>  rand(0,$innovationcount-3)
                )                
         );  
        
        
        // renders the view file 'protected/views/site/index.php'
        // using the default layout 'protected/views/layouts/main.php'
        $this->render('index',array(
            'advertisement'=>$advertisement,
            'product'=>$product,
            'innovation'=>$innovation,
        ));
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError() {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    public function actionContact() {
        $model = Contact::model()->findAll();
        $this->render('contact', array('model' => $model));
    }

    public function actionLeave() {
        $criteria = new CDbCriteria();
        $criteria->order = 'createtime desc';
        $criteria->condition='validate=1';
        $count = Leave::model()->count($criteria);
        $pages = new CPagination($count);
        // elements per page
        $pages->pageSize = 2;
        $pages->applyLimit($criteria);

        $models = Leave::model()->findAll($criteria);
        
        $Leavemodel=new Leave;
        $message='f';
        
        if(isset($_POST['Leave']))
	{
            $Leavemodel->attributes=$_POST['Leave'];
            $Leavemodel->createtime=date('Y-m-d H:i:s', time());
            //$Leavemodel->content='<h2>'.$Leavemodel->content."</h2>";
            if($Leavemodel->save()) {
                   $message='t';
                   $Leavemodel->content='';
            }

	}
        
        $this->render('leave', array(
            'models' => $models,
            'pages' => $pages,
            'leavemodel'=>$Leavemodel,
            'message'=>$message,
        ));
        
    }

    /**
     * Displays the login page
     */
    public function actionLogin() {
        $model = new LoginForm;

        // if it is ajax validation request
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        // collect user input data
        if (isset($_POST['LoginForm'])) {
            $model->attributes = $_POST['LoginForm'];
            // validate user input and redirect to the previous page if valid
            if ($model->validate() && $model->login())
                $this->redirect(array('/admin'));
        }
        // display the login form
        $this->render('login', array('model' => $model));
    }

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout() {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }
    
    public function actionProduct($tid=0){
        $criteria = new CDbCriteria();
        $criteria->order = 'id desc';
        if($tid!==0) {
            $criteria->condition='typeid=:tid';
            $criteria->params=array(':tid'=>$tid);
        }
        $count = Product::model()->count($criteria);
        $pages = new CPagination($count);
        // elements per page
        $pages->pageSize = 8;
        $pages->applyLimit($criteria);
        
        $type=  ProductType::model()->findAll();
        $models = Product::model()->findAll($criteria);
        
         $this->render('product', array(
            'models' => $models,
             'type'=> $type,
            'pages' => $pages,
        ));
    }
    
    public function actionInnovation($tid=0) {
        $criteria = new CDbCriteria();
        $criteria->order = 'id desc';
        if($tid!==0) {
            $criteria->condition='typeid=:tid';
            $criteria->params=array(':tid'=>$tid);
        }
        $count = Innovation::model()->count($criteria);
        $pages = new CPagination($count);
        // elements per page
        $pages->pageSize = 8;
        $pages->applyLimit($criteria);

        $models = Innovation::model()->findAll($criteria);
        $type= InnovationType::model()->findAll();
        
         $this->render('innovation', array(
            'models' => $models,
            'type'=> $type,
            'pages' => $pages,
        ));
    }
    
    public function actionAbout() {
         $about=About::model()->find();
         $this->render('about', array(
            'models' => $about,
        ));
    }
    
    public function actionEquipment() {
        $model = Equipment::model()->findAll();
        $this->render('equipment', array('model' => $model));
    }
    
    public function actionSearch($key='') {
        
        if($key!=='') {
           $key="%".$key."%";
           $connection=Yii::app()->db;
           $sql='(select * from tbl_product WHERE name LIKE :key) UNION ALL (select * from tbl_innovation WHERE name LIKE :key)';
           $command=$connection->createCommand($sql);
           $command->bindParam(":key",$key,PDO::PARAM_STR);
           $rows=$command->query();
           
           $criteria=new CDbCriteria();
           $pages=new CPagination($rows->rowCount);
           $pages->pageSize=8;
           $pages->applyLimit($criteria);
           
           $result=Yii::app()->db->createCommand($sql." LIMIT :offset,:limit");
           $result->bindParam(":key",$key,PDO::PARAM_STR);
           $result->bindValue(':offset', $pages->currentPage*$pages->pageSize);
           $result->bindValue(':limit', $pages->pageSize);
           $models=$result->queryAll();    

           //exit;
           if($models==null) {
                $this->render('search',array('info'=>'没有为您找到相关信息！',                
           ));
           }else {        
                $this->render('search',array(
                    'models'=>$models,
                    'pages'=>$pages,
                ));
           }
        }else {
            $this->render('search',array(
                'info'=>'您的查询条件为空值，请重输！',                
           ));
        }

    }
}

Leyecms/protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

Leyecms/protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

Leyecms/protected/views/layouts/main.php
<?php 
    $site=  SiteInfo::model()->find();
?>
    
<!DOCTYPE html>
<html lang="zh">
<head>
  <meta charset="utf-8">
  <title>昆山佳腾光电塑胶有限公司</title>
  <meta name="keywords" content="<?php echo $site->Keyword;?>"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta name="description" content="<?php echo $site->sitename;?>"/>
  <meta name="author" content="<?php echo $site->adminemail;?>"/>


	
  <link href="<?php echo Yii::app()->request->baseUrl.'/assets/bootstrap/';?>css/bootstrap.min.css" rel="stylesheet">
  <link href="<?php echo Yii::app()->request->baseUrl.'/assets/bootstrap/';?>css/bootstrap-responsive.min.css" rel="stylesheet">
  <link href="<?php echo Yii::app()->request->baseUrl.'/assets/bootstrap/';?>css/style.css" rel="stylesheet">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="<?php echo Yii::app()->request->baseUrl.'/assets/bootstrap/';?>js/html5shiv.js"></script>
  <![endif]-->

  <!-- Fav and touch icons -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo Yii::app()->request->baseUrl.'/assets/bootstrap/';?>img/apple-touch-icon-144-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo Yii::app()->request->baseUrl.'/assets/bootstrap/';?>img/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo Yii::app()->request->baseUrl.'/assets/bootstrap/';?>img/apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="<?php echo Yii::app()->request->baseUrl.'/assets/bootstrap/';?>img/apple-touch-icon-57-precomposed.png">
  <link rel="shortcut icon" href="<?php echo Yii::app()->request->baseUrl.'/assets/bootstrap/';?>img/favicon.gif">

</head>

<body>

<!-- logo -->
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span8">
			<img style="padding-bottom:15px;" src="<?php echo Yii::app()->request->baseUrl.'/assets/bootstrap/';?>img/logo.gif">
		</div>
		<div class="span4">
                    <?php echo CHtml::beginForm(array('site/search'), 'get',array('class'=>'form-search form-inline')); ?>
				<input name='key' class="input-medium search-query" type="text">
                                <input type="submit" class="btn" value="Search"/>
		    </form>
		</div>
	</div>
 
	<!-- nav-->
	<div class="row-fluid">
		<div class="span12">
			<ul id="navtop" class="nav nav-pills">
				<li>
                                        <?php echo CHtml::link('首页', array("/site/index"));?>
				</li>
				<li>
					  <?php echo CHtml::link('产品', array("/site/product"));?>
				</li>
				<li>
                                         <?php echo CHtml::link('资源', array("/site/innovation"));?>
				</li>
				<li class="dropdown pull-right">
					 <a href="#" data-toggle="dropdown" class="dropdown-toggle">更多..<strong class="caret"></strong></a>
					<ul class="dropdown-menu">
						<li>
                                                        <?php echo CHtml::link('联系我们', array("/site/contact"));?>
						</li>
                                                <li>
                                                        <?php echo CHtml::link('访客留言', array("/site/leave"));?>
                                                </li>
						<li class="divider">
						</li>
						<li>   <?php 
                                                        if(Yii::app()->user->isGuest) {
                                                       ?>
                                                            <?php echo CHtml::link('登录', array("/site/login"));?>
                                                        <?php
                                                        }else {
                                                        ?>
                                                            <?php echo CHtml::link('登出', array("/site/logout"));?>
                                                        <?php                                                 
                                                        }
                                                        ?>
						</li>
					</ul>
				</li>
			</ul>
		</div>
	</div>

        <?php echo $content;?>
        
<!-- footer -->
        <hr>
	<div class="row-fluid">
	<div class="span2">
			<img src="<?php echo Yii::app()->request->baseUrl.'/upload/attachment/13867716355405.gif';?>">
	</div>
        <div id="footer" class="span10">
            <p class="text-center"><?php echo $site->Copyright;?><br/>
		地址:江苏省昆山市张浦镇江丰路168号 电话:+86-512-5745 1658<br/>  	
        	</p>
    	</div>
	</div>

</div>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl.'/assets/bootstrap/';?>js/jquery-1.10.2.min.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl.'/assets/bootstrap/';?>js/bootstrap.min.js"></script>
</body>
</html>